version: "3.5"

services:
  analyzer:
    build: .
    image: lingfennan/codeql-analyzer:latest
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./:/src/
      - ./bad-overflow-guard/:/root/codeql-repo/cpp/ql/src/bad-overflow-guard/

